### ISSUE TITLE
Amiibo do work on prodinfo from scratch

### ISSUE THREAD

**Issue by Fahim732** [CaramelDunes/prodinfo_gen#12]
I injected prodinfo from scratch on my unpatched erista console's emummc, I disabled emuiibo and tried my legit MP-Peach amiibo. It did worked just fine right out of the box. Also amiibo works in settings, tested in two games also.

**Comment by CaramelDunes** [comment]
That's great news! Thanks a lot for your feedback, I will update the README accordingly.

We still don't know what are the Amiibo fields for, though...
