### ISSUE TITLE
Device ID has one number off

### ISSUE THREAD

**Issue by Wat6656** [CaramelDunes/prodinfo_gen#13]
Great work on this!!!! I have noticed that when the payload extracts the device id the first 0 is replaced by a 3. I have tested this on a few consoles, curious what the reason could be? I

**Comment by CaramelDunes** [comment]
Hi @Wat6656, thanks for the kind words.

It comes from the fact that the leading two nibbles of the device id cannot be derived from fuses. Commit 539ab4a8fff11785c56fff77d3bac7101751b424 "addresses" this by explicitly choosing 0 as the second nibble to show that we don't know its original value. It doesn't affect anything as those first two characters are not checked by the Switch when booting.
The first nibble is always 6.
