### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by 1619534** [CaramelDunes/prodinfo_gen#16]
error: initializer element is not constant

**Comment by CaramelDunes** [comment]
Could you share more information about the error? Any context or line number?

**Comment by 1619534** [comment]
OS: debian 10.x 64bit
GNU Make 4.2.1
gcc version 8.3.0


root@debian:/home/user/prodinfo_gen-master# DEVKITARM=/opt/devkitpro/devkitARM make
arm-none-eabi-gcc -march=armv4t -mtune=arm7tdmi -mthumb -mthumb-interwork -Os -nostdlib -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-inline -std=gnu11 -Wall -DIPL_LOAD_ADDR=0x40003000 -DLP_VER_MJ=0 -DLP_VER_MN=3 -DLP_VER_BF=4 -DGFX_INC='"../source/gfx/gfx.h"' -DFFCFG_INC='"../source/libs/fatfs/ffconf.h"' -I./bdk -c source/cal0/cal0.c -o build/prodinfo_gen/cal0/cal0.o
In file included from source/cal0/cal0.c:27:0:
source/cal0/cal_blocks.h:111:14: error: initializer element is not constant
     BLOCK_OF(ConfigurationId1), // DEFAULT MP_00_01_00_00
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:111:14: note: (near initialization for 'base_crc_blocks[0]')
     BLOCK_OF(ConfigurationId1), // DEFAULT MP_00_01_00_00
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:113:14: error: initializer element is not constant
     BLOCK_OF(WlanCountryCodes), // DEFAULT
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:113:14: note: (near initialization for 'base_crc_blocks[1]')
     BLOCK_OF(WlanCountryCodes), // DEFAULT
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:115:14: error: initializer element is not constant
     BLOCK_OF(WlanMacAddress),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:115:14: note: (near initialization for 'base_crc_blocks[2]')
     BLOCK_OF(WlanMacAddress),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:116:14: error: initializer element is not constant
     BLOCK_OF(BtMacAddress),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:116:14: note: (near initialization for 'base_crc_blocks[3]')
     BLOCK_OF(BtMacAddress),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:118:14: error: initializer element is not constant
     BLOCK_OF(AccelerometerOffset),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:118:14: note: (near initialization for 'base_crc_blocks[4]')
     BLOCK_OF(AccelerometerOffset),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:119:14: error: initializer element is not constant
     BLOCK_OF(AccelerometerScale),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:119:14: note: (near initialization for 'base_crc_blocks[5]')
     BLOCK_OF(AccelerometerScale),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:120:14: error: initializer element is not constant
     BLOCK_OF(GyroscopeOffset),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:120:14: note: (near initialization for 'base_crc_blocks[6]')
     BLOCK_OF(GyroscopeOffset),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:121:14: error: initializer element is not constant
     BLOCK_OF(GyroscopeScale),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:121:14: note: (near initialization for 'base_crc_blocks[7]')
     BLOCK_OF(GyroscopeScale),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:122:14: error: initializer element is not constant
     BLOCK_OF(SerialNumber),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:122:14: note: (near initialization for 'base_crc_blocks[8]')
     BLOCK_OF(SerialNumber),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:124:14: error: initializer element is not constant
     BLOCK_OF(EccP256DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:124:14: note: (near initialization for 'base_crc_blocks[9]')
     BLOCK_OF(EccP256DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:125:14: error: initializer element is not constant
     BLOCK_OF(EccP256DeviceCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:125:14: note: (near initialization for 'base_crc_blocks[10]')
     BLOCK_OF(EccP256DeviceCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:126:14: error: initializer element is not constant
     BLOCK_OF(EccB233DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:126:14: note: (near initialization for 'base_crc_blocks[11]')
     BLOCK_OF(EccB233DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:128:14: error: initializer element is not constant
     BLOCK_OF(EccB233DeviceCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:128:14: note: (near initialization for 'base_crc_blocks[12]')
     BLOCK_OF(EccB233DeviceCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:130:14: error: initializer element is not constant
     BLOCK_OF(EccP256ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:130:14: note: (near initialization for 'base_crc_blocks[13]')
     BLOCK_OF(EccP256ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:131:14: error: initializer element is not constant
     BLOCK_OF(EccP256ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:131:14: note: (near initialization for 'base_crc_blocks[14]')
     BLOCK_OF(EccP256ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:132:14: error: initializer element is not constant
     BLOCK_OF(EccB233ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:132:14: note: (near initialization for 'base_crc_blocks[15]')
     BLOCK_OF(EccB233ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:133:14: error: initializer element is not constant
     BLOCK_OF(EccB233ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:133:14: note: (near initialization for 'base_crc_blocks[16]')
     BLOCK_OF(EccB233ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:135:14: error: initializer element is not constant
     BLOCK_OF(SslKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:135:14: note: (near initialization for 'base_crc_blocks[17]')
     BLOCK_OF(SslKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:136:14: error: initializer element is not constant
     BLOCK_OF(SslCertificateSize),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:136:14: note: (near initialization for 'base_crc_blocks[18]')
     BLOCK_OF(SslCertificateSize),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:138:14: error: initializer element is not constant
     BLOCK_OF(GameCardKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:138:14: note: (near initialization for 'base_crc_blocks[19]')
     BLOCK_OF(GameCardKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:140:14: error: initializer element is not constant
     BLOCK_OF(Rsa2048ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:140:14: note: (near initialization for 'base_crc_blocks[20]')
     BLOCK_OF(Rsa2048ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:141:14: error: initializer element is not constant
     BLOCK_OF(Rsa2048ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:141:14: note: (near initialization for 'base_crc_blocks[21]')
     BLOCK_OF(Rsa2048ETicketCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:143:14: error: initializer element is not constant
     BLOCK_OF(BatteryLot),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:143:14: note: (near initialization for 'base_crc_blocks[22]')
     BLOCK_OF(BatteryLot),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:144:14: error: initializer element is not constant
     BLOCK_OF(SpeakerCalibrationValue),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:144:14: note: (near initialization for 'base_crc_blocks[23]')
     BLOCK_OF(SpeakerCalibrationValue),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:146:14: error: initializer element is not constant
     BLOCK_OF(RegionCode),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:146:14: note: (near initialization for 'base_crc_blocks[24]')
     BLOCK_OF(RegionCode),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:148:14: error: initializer element is not constant
     BLOCK_OF(AmiiboKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:148:14: note: (near initialization for 'base_crc_blocks[25]')
     BLOCK_OF(AmiiboKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:149:14: error: initializer element is not constant
     BLOCK_OF(AmiiboEcqvCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:149:14: note: (near initialization for 'base_crc_blocks[26]')
     BLOCK_OF(AmiiboEcqvCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:150:14: error: initializer element is not constant
     BLOCK_OF(AmiiboEcdsaCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:150:14: note: (near initialization for 'base_crc_blocks[27]')
     BLOCK_OF(AmiiboEcdsaCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:151:14: error: initializer element is not constant
     BLOCK_OF(AmiiboEcqvBlsKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:151:14: note: (near initialization for 'base_crc_blocks[28]')
     BLOCK_OF(AmiiboEcqvBlsKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:152:14: error: initializer element is not constant
     BLOCK_OF(AmiiboEcqvBlsCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:152:14: note: (near initialization for 'base_crc_blocks[29]')
     BLOCK_OF(AmiiboEcqvBlsCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:153:14: error: initializer element is not constant
     BLOCK_OF(AmiiboEcqvBlsRootCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:153:14: note: (near initialization for 'base_crc_blocks[30]')
     BLOCK_OF(AmiiboEcqvBlsRootCertificate),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:155:14: error: initializer element is not constant
     BLOCK_OF(ProductModel),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:155:14: note: (near initialization for 'base_crc_blocks[31]')
     BLOCK_OF(ProductModel),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:156:14: error: initializer element is not constant
     BLOCK_OF(ColorVariation),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:156:14: note: (near initialization for 'base_crc_blocks[32]')
     BLOCK_OF(ColorVariation),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:157:14: error: initializer element is not constant
     BLOCK_OF(LcdBacklightBrightnessMapping),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:157:14: note: (near initialization for 'base_crc_blocks[33]')
     BLOCK_OF(LcdBacklightBrightnessMapping),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:159:14: error: initializer element is not constant
     BLOCK_OF(ExtendedEccB233DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:159:14: note: (near initialization for 'base_crc_blocks[34]')
     BLOCK_OF(ExtendedEccB233DeviceKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:160:14: error: initializer element is not constant
     BLOCK_OF(ExtendedEccP256ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:160:14: note: (near initialization for 'base_crc_blocks[35]')
     BLOCK_OF(ExtendedEccP256ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:161:14: error: initializer element is not constant
     BLOCK_OF(ExtendedEccB233ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:161:14: note: (near initialization for 'base_crc_blocks[36]')
     BLOCK_OF(ExtendedEccB233ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:162:14: error: initializer element is not constant
     BLOCK_OF(ExtendedRsa2048ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:162:14: note: (near initialization for 'base_crc_blocks[37]')
     BLOCK_OF(ExtendedRsa2048ETicketKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:163:14: error: initializer element is not constant
     BLOCK_OF(ExtendedSslKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:163:14: note: (near initialization for 'base_crc_blocks[38]')
     BLOCK_OF(ExtendedSslKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:164:14: error: initializer element is not constant
     BLOCK_OF(ExtendedGameCardKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:164:14: note: (near initialization for 'base_crc_blocks[39]')
     BLOCK_OF(ExtendedGameCardKey),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:165:14: error: initializer element is not constant
     BLOCK_OF(LcdVendorId)};
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:165:14: note: (near initialization for 'base_crc_blocks[40]')
     BLOCK_OF(LcdVendorId)};
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:174:14: error: initializer element is not constant
     BLOCK_OF(HousingSubColor),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:174:14: note: (near initialization for 'bonus_crc_blocks[0]')
     BLOCK_OF(HousingSubColor),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:175:14: error: initializer element is not constant
     BLOCK_OF(HousingBezelColor),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:175:14: note: (near initialization for 'bonus_crc_blocks[1]')
     BLOCK_OF(HousingBezelColor),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:176:14: error: initializer element is not constant
     BLOCK_OF(HousingMainColor1),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:176:14: note: (near initialization for 'bonus_crc_blocks[2]')
     BLOCK_OF(HousingMainColor1),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:177:14: error: initializer element is not constant
     BLOCK_OF(HousingMainColor2),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:177:14: note: (near initialization for 'bonus_crc_blocks[3]')
     BLOCK_OF(HousingMainColor2),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:178:14: error: initializer element is not constant
     BLOCK_OF(HousingMainColor3),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:178:14: note: (near initialization for 'bonus_crc_blocks[4]')
     BLOCK_OF(HousingMainColor3),
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:194:14: error: initializer element is not constant
     BLOCK_OF(ColorModel)
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
source/cal0/cal_blocks.h:194:14: note: (near initialization for 'bonus_crc_blocks[5]')
     BLOCK_OF(ColorModel)
              ^
source/cal0/cal_blocks.h:22:24: note: in definition of macro 'BLOCK_OF'
 #define BLOCK_OF(name) name##_block
                        ^~~~
make: *** [Makefile:76：build/prodinfo_gen/cal0/cal0.o] 错误 1

**Comment by CaramelDunes** [comment]
It's probably a matter of upgrading your devkitARM, it works on my side with the latest release: `gcc version 11.1.0 (devkitARM release 56)` (using `/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc -v`)
