### ISSUE TITLE
Personalized serial number

### ISSUE THREAD

**Issue by lsp199308** [CaramelDunes/prodinfo_gen#17]
Is it possible to not erase the serial number, in the scratch creation the serial number was set to xac000000000, I lost my original prodinfo but I would like to personalize the serial number, for example xaj888888888

Please excuse my English, my English is very bad

Thank you for your great dedication

**Comment by CaramelDunes** [comment]
Hi @lsp199308,

Unfortunately, this feature isn't supported by prodinfo_gen at the moment.

**Option 1:** Edit this line https://github.com/CaramelDunes/prodinfo_gen/blob/358f5a6788b4113f578a9cae23dbbda53241d291/source/cal0/cal0.c#L364 and rebuild the payload.

**Option 2:** Edit the generated prodinfo manually with a hex editor, following this binary format: https://switchbrew.org/wiki/Calibration

Note that the serial number in a generated prodinfo has no functional purpose and can be set to anything.

Hope this helps.

**Comment by lsp199308** [comment]
Thank you very much, it has been solved.
