### ISSUE TITLE
Personalized serial number

### ISSUE THREAD

**Issue by lsp199308** [CaramelDunes/prodinfo_gen#18]
I wonder if the personalized serial number could be read from sd/serial_number.txt 
so that we would not have to compile prodinfo_gen again
This is just a suggestion, thank you for your great work and for allowing me to fix my prodinfo

**Comment by lsp199308** [comment]
I have changed it to XKJ8888888888 by the method you provided, but if I want to change it again I need to recompile prodinfo_gen, so if there is an easy way to do it, that's good, well, I also tried Chinese and it worked fine, English is my second language, please forgive me, my English is really bad

**Comment by CaramelDunes** [comment]
You could modify the prodinfo with a hex editor, you'll need to update the checksums accordingly. This should be easier than rebuilding `prodinfo_gen`. Thanks for the suggestion, but I'm not gonna do that, the serial number is purely cosmetic AFAIK.

**Comment by DraconicNEO** [comment]
> Hi @lsp199308, why would you need a custom serial number?

Well being able to set your Serial Number (either as the original or as a custom one) can partially remedy certain issues that come from having a serial number that's all zeros, especially in countries that aren't too fond of modding.

**Comment by lsp199308** [comment]
> > Hi @lsp199308, why would you need a custom serial number?
> 
> 
> 
> Well being able to set your Serial Number (either as the original or as a custom one) can partially remedy certain issues that come from having a serial number that's all zeros, especially in countries that aren't too fond of modding.

This has no real meaning, it's just a personalized setting, I'm in China and use Chinese characters
