### ISSUE TITLE
Gamecard not working

### ISSUE THREAD

**Issue by Adran-Marit** [CaramelDunes/prodinfo_gen#2]
After generating a prodinfo from a donor (incognito'd) attemtpting to boot via atmosphere results in a fatal crash just after the nintendo switch logo when a gamecard is inserted into the console or thereafter if a game is inserted.  

Things I did to reach this conclusion

- Have a donor prodinfo labelled as required per documentation
- place donor_prodinfo in the switch folder
- launch prodinfo_gen payload
- generated prodinfo from donor
- copied to pc
- flashed prodinfo to switch via hacdiskmount with correct keys
- booted atmosphere 0.15.0 - experimental (cool kids)
- Switch booted to switch logo then hit a fatal error
- removed gamecard
- rebooted atmosphere, console booted
- inserted gamecard, console crashed with same fatal as before

**Comment by CaramelDunes** [comment]
Hi Adran-Marit, thanks for your report! I just got access to a gamecard and will now be able to look into this.

**Comment by Adran-Marit** [comment]
Cheers for looking into it

**Comment by Adran-Marit** [comment]
Any updates on this??

**Comment by CaramelDunes** [comment]
Once I have the necessary keks to reencrypt the PRODINFO ExtendedGamecardKey, I should be able to make it work.

**Comment by laotoulyh** [comment]
keks may be in kfuse.bin
