### ISSUE TITLE
Please update the version available for OLED models.

### ISSUE THREAD

**Issue by laotoulyh** [CaramelDunes/prodinfo_gen#20]
Hello, the OLED model runs 0.33 0.34 and all have a black screen, but in actual operation, it can be generated normally by pressing the power button, and the prodinfo of oled is a bit different. I hope you can update it.

**Comment by CaramelDunes** [comment]
If I understand correctly, you say that prodinfo_gen works but doesn't show anything? Makes sense, I need to upgrade to Hekate's newest BDK.
I'm curious about how the OLED prodinfo is different, I'd be grateful if you could send me one (feel free to strip SSL key/certificates, send to dev@carameldunes.fr).

In any case, thanks a lot for reporting this to me :)

**Comment by laotoulyh** [comment]
Sent!
Please contact me if you need anything else!

**Comment by CaramelDunes** [comment]
Here it is! https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.0.0

I'd really appreciate it if you could test it a little bit. Making sure that it still works for previous models, if possible.
Thanks :-)

**Comment by laotoulyh** [comment]
I tested it with OLED just now, the SCRATCH method will stay in JOYCON LOGO, but it can work with DONOR.

Another friend test also had the same result.

**Comment by CaramelDunes** [comment]
Thanks! It's actually something I've already fixed in the past 🙈 
If you could try again, and maybe on older consoles too :-)
https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.0.1

**Comment by laotoulyh** [comment]
I tested the OLED and Mariko models, and both scratch and donor can work.

**Comment by CaramelDunes** [comment]
Many thanks 👍

**Comment by laotoulyh** [comment]
I just tested that Erista also works.
