### ISSUE TITLE
PRODINFO BACK-UP LOST

### ISSUE THREAD

**Issue by vaccarieli** [CaramelDunes/prodinfo_gen#23]
Hello, just want to know wether is possible or not to recover my lost Prodinfo, I guess I know what my answer will be, but I still want to double check.

What happened is that I had blank my prodinfo on my console to prevent getting banned 2 years ago and lost the SD card where the backup was saved on.

I know my serial number and have my blank prodinfo which I got by doing a backup to the one on my console already.

My question is, is there a way to get that prodinfo file, the serial number back to that blank prodinfo copy I have?

**Comment by CaramelDunes** [comment]
If blanked using Incognito, you're out of luck, as it wipes some certs required to connect to Nintendo Servers.
