### ISSUE TITLE
prondinfo gen does not work in 14.0.0

### ISSUE THREAD

**Issue by lsp199308** [CaramelDunes/prodinfo_gen#24]
I used prondinfo gen to recover my prondinfo, in hos 14.0.0 he failed

https://github.com/Atmosphere-NX/Atmosphere/issues/1805

**Comment by laotoulyh** [comment]
Yes, I tried it with mariko and erista, but after both are JOYCON LOGO, I get an error 2105-0584

**Comment by laotoulyh** [comment]
![image](https://user-images.githubusercontent.com/76421243/160070528-b7f04976-f611-4f3b-a810-4c67977a37e6.png)

**Comment by stanz328** [comment]
> ![image](https://user-images.githubusercontent.com/76421243/160070528-b7f04976-f611-4f3b-a810-4c67977a37e6.png)

![Uploading IMG-20220325-WA0257.jpeg…]()

**Comment by CaramelDunes** [comment]
Thanks for the report, will try to investigate this weekend.

**Comment by CaramelDunes** [comment]
I've identified the cause, writing a patch 💪

**Comment by stanz328** [comment]
> I've identified the cause, writing a patch 💪 

😊😊😊😊appreciate for your hardwork on it 😍😍

**Comment by CaramelDunes** [comment]
Could someone try this please: https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0

**Comment by xiaojiangGangGang** [comment]
> 

I'm testing it.

**Comment by xiaojiangGangGang** [comment]
> Could someone try this please: https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0

I've turned it on normally

**Comment by xiaojiangGangGang** [comment]
> 有人可以试试这个吗：[https ://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0](https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0)

Insert tape error 2002-2667 What can fix this problem

**Comment by stanz328** [comment]
> > 有人可以试试这个吗：[https ://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0](https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0)
> 
> 
> 
> Insert tape error 2002-2667 What can fix this problem

Because u r using the scratch key and not the correct prod key 

rename your prod.key to donor.key
In switch folder To start over the process , hope it's help out

**Comment by CaramelDunes** [comment]
> > 有人可以试试这个吗：[https ://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0](https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0)
> 
> Insert tape error 2002-2667 What can fix this problem

This is expected if you're using a "from scratch" prodinfo.

If you can find a donor, you can use their gamecard cert and key, then it should work. Some prodinfo can be found on the internet.

**Comment by xiaojiangGangGang** [comment]
> > > 有人可以试试这个吗：https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0
> > 
> > 
> > 插入磁带错误 2002-2667 什么可以解决这个问题
> 
> 如果您使用的是“从头开始”的产品信息，则这是预期的。
> 
> 如果你能找到捐赠者，你可以使用他们的游戏卡证书和密钥，那么它应该可以工作。一些 prodinfo 可以在 Internet 上找到。

Can I use the decrypted PRODINFO from another host directly as from donor? Can I use his game card certificate and key to connect to Nintendo server

**Comment by CaramelDunes** [comment]
> > > > 有人可以试试这个吗：https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0
> > > 
> > > 
> > > 插入磁带错误 2002-2667 什么可以解决这个问题
> > 
> > 如果您使用的是“从头开始”的产品信息，则这是预期的。
> > 
> > 如果你能找到捐赠者，你可以使用他们的游戏卡证书和密钥，那么它应该可以工作。一些 prodinfo 可以在 Internet 上找到。
> 
> Can I use the decrypted PRODINFO from another host directly as from donor?

Yes. If it is from a patched or Mariko console, you'll need its keys. 


> Can I use his game card certificate and key to connect to Nintendo server

No, a gamecard certificate is only to be able to read gamecards.

**Comment by CaramelDunes** [comment]
> > Could someone try this please: https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0
> 
> I've turned it on normally

Thank you! @xiaojiangGangGang

Could I get a second, independent test, for good measure, please? :+1:

**Comment by lsp199308** [comment]
He worked very well in mariko, thank you very much

**Comment by stanz328** [comment]
> > > Could someone try this please: https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0
> 
> > 
> 
> > I've turned it on normally
> 
> 
> 
> Thank you! @xiaojiangGangGang
> 
> 
> 
> Could I get a second, independent test, for good measure, please? :+1:

I will test in one unit of Mariko V2 and one unit of OLED consoles , report back in next day , thanks MR Lucas

**Comment by CaramelDunes** [comment]
Thanks everyone!

**Comment by xiaojiangGangGang** [comment]
> > > 有人可以试试这个吗：https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0
> > 
> > 
> > 我已经正常开启了
> 
> 谢谢！@xiaojiangGangGang
> 
> 我可以进行第二次独立测试吗？👍

****

**Comment by ghost** [comment]
I found a way to solve the problem without doing too much manipulation:

From a blank SD card, which will only be used for manipulation, we create an EmuNand, and then once on your EmuNand,

You are updating with daybreak to 14.X.X .

Once the last update is done, take your sd in the computer you open NxNandManager (5.2). You go to PRODINFO, you make a dump of it.

You then insert your SD card with the boot crash error as indicated above, and load your card in NxNandManager.

You go to PRODINFO, you make a dump of it for security.

Then, you right-click on PRODINFO and "restore from file" and you will indicate the PRODINFO that you dumped before on the blank SD card.

**Comment by Asenvivie** [comment]
> Could someone try this please: https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v1.1.0

Sir, can you teach me how to use this. Im noob for like this. I have same error
