### ISSUE TITLE
Prodinfo fail in firmware 14.0

### ISSUE THREAD

**Issue by stanz328** [CaramelDunes/prodinfo_gen#25]
2 unis of Mariko Prodinfo donor nand consoles update from 13.2.1 to 14.0 failed to start up.

![IMG-20220325-WA0257](https://user-images.githubusercontent.com/91884900/160145420-06fd6947-f86c-4343-bdd7-17afb039a55e.jpeg)
![20220325_223944](https://user-images.githubusercontent.com/91884900/160145449-87074567-2c91-480f-8338-8937b68c1890.jpg)

Ofw start up - error code 2105-0584

Cfw start up - stuck on Nintendo switch logo

**Comment by CaramelDunes** [comment]
Thanks for the detailed report. 👍

**Comment by CaramelDunes** [comment]
Closing in favor of #24.
