### ISSUE TITLE
a few question

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [CaramelDunes/prodinfo_gen#26]
i have a few questions.

what is the maximum supported firmware version?

i want to use a donor prodinfo, i need to place the faulty switch prod.keys beside or the donor switch prod.keys ?

if i success making and using a generated prodinfo from donor, can i update with daybreak or i need to use emmchaccgen and nxnandmanager?

and i need to replace the boot0/boot1 from the donor switch or just replace the prodinfo?

if everything is went fine and i updated to 11.00 can i use sxos too or just ams only?

**Comment by stanz328** [comment]
1)maximum support up to 13.2.1 firmware ,will fail to boot into system on 14.0 , currently need to wait for the prodinfo_gen to update for support.

2)ur own faulty consoles prod key by lockpick rcm, the donor_prodkey is to match with the donor_rawnand.

3) u need both ,maximum up to 13.2.1 fw ,can't be higher for now .14.0 will crash when start up.

4) just the prodinfo will do.

5)ams only since the sx os webpage is shut down ,no way for u to activate it anymore.

**Comment by TheOneEyedGrimReaper** [comment]
> 1)maximum support up to 13.2.1 firmware ,will fail to boot into system on 14.0 , currently need to wait for the prodinfo_gen to update for support.
> 
> 2)ur own faulty consoles prod key by lockpick rcm, the donor_prodkey is to match with the donor_rawnand.
> 
> 3. u need both ,maximum up to 13.2.1 fw ,can't be higher for now .14.0 will crash when start up.
> 4. just the prodinfo will do.
> 
> 5)ams only since the sx os webpage is shut down ,no way for u to activate it anymore.

thanks, for the help.
i saved the faulty switch now with a very time consuming method, and created a guide for that too.
but if you say i can use just the donor switch rawnand and the prodinfo and prod.keys for donor, i can make the guide very short and easy.

**Comment by CaramelDunes** [comment]
> 1)maximum support up to 13.2.1 firmware ,will fail to boot into system on 14.0 , currently need to wait for the prodinfo_gen to update for support.
> 
> 2)ur own faulty consoles prod key by lockpick rcm, the donor_prodkey is to match with the donor_rawnand.
> 
>     3. u need both ,maximum up to 13.2.1 fw ,can't be higher for now .14.0 will crash when start up.
> 
>     4. just the prodinfo will do.
> 
> 
> 5)ams only since the sx os webpage is shut down ,no way for u to activate it anymore.

Thanks a lot for answering @stanz328 😃
