### ISSUE TITLE
Any way to get GameCards working from scratch

### ISSUE THREAD

**Issue by DraconicNEO** [CaramelDunes/prodinfo_gen#27]
Hey I was wondering, is there any way that we could somehow get GameCards working with prodinfo generated from scratch? What is it exactly that prevents them from working when we do generate it from scratch?

**Comment by Masamune3210** [comment]
Gamecard cert probably

**Comment by DraconicNEO** [comment]
> Gamecard cert probably

Probably, hopefully there's some kind of work around to get them working since gamecards are useful in that they save space that would be used by the game on the SD card.

**Comment by CaramelDunes** [comment]
You should be able to find donor prodinfos online that will let you use the GameCard reader.

**Comment by DraconicNEO** [comment]
> You should be able to find donor prodinfos online that will let you use the GameCard reader.

Oh that's definitely a much simpler solution, why didn't I think of that.
