### ISSUE TITLE
Can a generator supporting mariko's prodinfo be made?

### ISSUE THREAD

**Issue by laotoulyh** [CaramelDunes/prodinfo_gen#3]
The generated prodinfo file, used by mariko, will get stuck in the second LOGO.
Erista is OK.

**Comment by CaramelDunes** [comment]
By second logo you mean the Nintendo Switch logo? 
Launching prodinfo_gen on Mariko is not yet supported, how did you generate the prodinfo file?

**Comment by CaramelDunes** [comment]
I just pre-released a compatible version https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v0.2.0-beta
I'd love if you could try it, thanks!
