### ISSUE TITLE
SSL Import Payload

### ISSUE THREAD

**Issue by surivaton** [CaramelDunes/prodinfo_gen#38]
@CaramelDunes its more a question since i have changed my Device ID and i need to import a SSL Cert to have connection.
Can you link me the payload? if yes i want to show you something private about generating a new cert of the nintendo switch.
Thanks in advance.

**Comment by CostelaCNX** [comment]
Is no possible using cert from one switch to another without gen a deviceid

**Comment by surivaton** [comment]
> Is no possible using cert from one switch to another without gen a deviceid

i know thats why i am asking for the payload from @CaramelDunes i got it booted with a other device id but i need to import the ssl cert. there was a discussion about it so: https://github.com/CaramelDunes/prodinfo_gen/issues/15

**Comment by CostelaCNX** [comment]
You boot on HOS without cfw using another deviceid?

**Comment by surivaton** [comment]
> You boot on HOS without cfw using another deviceid?

i use CFW with a custom prodinfo with another deviceid, the only problem is the SSL cert to make connection with the nintendo servers. im busy with something.

**Comment by surivaton** [comment]
Look a little preview 😎
![Snapchat-1338281814](https://github.com/user-attachments/assets/567d4142-6d92-4651-8d4a-befa5661fe22)
![Snapchat-901858211](https://github.com/user-attachments/assets/c5312348-aeb8-4259-9472-452714e9dc32)
![Snapchat-1762591744](https://github.com/user-attachments/assets/7f43c112-0615-44d9-9871-339346557ec2)

**Comment by surivaton** [comment]
@CaramelDunes let me know if u got the SSL import payload still available.

**Comment by surivaton** [comment]
Nvm problem is solved, got it working!
