### ISSUE TITLE
mariko test

### ISSUE THREAD

**Issue by laotoulyh** [CaramelDunes/prodinfo_gen#7]
"from scratch" PRODINFO
Booting is work
Launching homebrews is work

"from donor" PRODINFO:

Booting is not work, get stuck in Nintendo Switch logo.

I have tested that using mariko's prodinfo.bin or erista's prodinfo.bin as donor_prodinf.bin can not work.

I have various models of switches. If you want to find someone to test, you can contact my telegram account: @laotoulyh

**Comment by CaramelDunes** [comment]
Thanks, I should have updated the README accordingly. Only "from scratch" currently works for Mariko as the prodinfo keys are personnalized in the donor prodinfo. I know how to deal with it, but it is less important than getting the GameCard to work.

**Comment by laotoulyh** [comment]
0.2.1 test:
"from scratch" PRODINFO
After booting to the Nintendo Switch logo, error 2011-0301 is reported

**Comment by CaramelDunes** [comment]
You mean it was working before 0.2.1 and now it is not?

**Comment by CaramelDunes** [comment]
It is probably because you have a GameCard inserted. GameCard is only supported with "from donor" . "from donor" is not yet supported for Mariko units.

**Comment by CaramelDunes** [comment]
Thanks for the feedback though! Support for Mariko units should come in a couple of days.

**Comment by laotoulyh** [comment]
I did not insert a game card.

**Comment by CaramelDunes** [comment]
> 
> 
> 0.2.1 test:
> "from scratch" PRODINFO
> After booting to the Nintendo Switch logo, error 2011-0301 is reported

Did it work after rebooting just once?

**Comment by CaramelDunes** [comment]
Whenever you have time, could you try importing from a Mariko PRODINFO with the latest release? https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v0.3.0-beta
Thanks!

**Comment by laotoulyh** [comment]
0.3.0 test:
Importing from a Mariko PRODINFO
After booting to the Nintendo Switch logo, error 2011-0301 is reported

**Comment by CaramelDunes** [comment]
Even after rebooting by pressing the Power button on the error screen?
Did the PRODINFO generation go fine? Any errors or warnings?

**Comment by CaramelDunes** [comment]
There was actually a bug in the certificate importing code. Could you retry with https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v0.3.1-beta ? Thanks a lot for testing!

**Comment by laotoulyh** [comment]
Even after rebooting by pressing the Power button on the error screen?
Will get stuck in Nintendo Switch logo.
Did the PRODINFO generation go fine? Any errors or warnings?
Fine, no any error or warning.

**Comment by laotoulyh** [comment]
0.3.1 test is ok!

**Comment by CaramelDunes** [comment]
Are you still having 2011-0301 with "from scratch"?

**Comment by laotoulyh** [comment]
> Are you still having 2011-0301 with "from scratch"?

Yes, 0.3.1 still 2011-0301

**Comment by CaramelDunes** [comment]
Hum, that's weird, what kind of Switch is that?

**Comment by laotoulyh** [comment]
> Hum, that's weird, what kind of Switch is that?

mariko

**Comment by CaramelDunes** [comment]
Interesting, on Erista Switches it only happens when a GameCard is inserted.

> 
> 
> "from scratch" PRODINFO
> Booting is work
> Launching homebrews is work

Does that mean you didn't have that problem before?

**Comment by laotoulyh** [comment]
> Interesting, on Erista Switches it only happens when a GameCard is inserted.
> 
> > "from scratch" PRODINFO
> > Booting is work
> > Launching homebrews is work
> 
> Does that mean you didn't have that problem before?

Yes, 0.2.0's "from scratch"  is ok.

**Comment by laotoulyh** [comment]
This is not important, but is there any way to solve the problem with SSL certificate?

**Comment by laotoulyh** [comment]
I have sent a good donor_prodinfo.bin to dev@carameldunes.fr, you can test it.

**Comment by CaramelDunes** [comment]
You mean you want to import the SSL certificate to connect to Nintendo online services?
If so, it is possible to import it, but as I'm pretty sure it will lead to the cert getting banned I don't want to implement the feature.

**Comment by CaramelDunes** [comment]
> 
> 
> I have sent a good donor_prodinfo.bin to [dev@carameldunes.fr](mailto:dev@carameldunes.fr), you can test it.

Thanks a lot!

**Comment by laotoulyh** [comment]
> You mean you want to import the SSL certificate to connect to Nintendo online services?
> If so, it is possible to import it, but as I'm pretty sure it will lead to the cert getting banned I don't want to implement the feature.

If possible, I hope you can provide the function to change, let us choose whether to use it.

**Comment by laotoulyh** [comment]
If you want to find someone to test, you can contact my telegram account: @laotoulyh

**Comment by CaramelDunes** [comment]
https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v0.3.2-beta should fix 2011-0301 when using a "from scratch" PRODINFO.

**Comment by laotoulyh** [comment]
> https://github.com/CaramelDunes/prodinfo_gen/releases/tag/v0.3.2-beta should fix 2011-0301 when using a "from scratch" PRODINFO.

0.3.2's "from scratch" is ok.

**Comment by laotoulyh** [comment]
Hope you can resolve the SSL certificate.

**Comment by sthetix** [comment]
I tested on Mariko (lite), on 0.3.3, and it is stuck on the Nintendo Switch Logo.
FYI, Original prodinfo works.

**Comment by CaramelDunes** [comment]
> 
> 
> I tested on Mariko (lite), on 0.3.3, and it is stuck on the Nintendo Switch Logo.
> FYI, Original prodinfo works.

Hi sthetix, thanks for the report! You are talking about a "from scratch" prodinfo, right?

You might well be the first to test on a Switch Lite. Could you please send me the generated prodinfo and, if possible, the original prodinfo (you can redact the certs away) at dev@carameldunes.fr?

**Comment by sthetix** [comment]
> > I tested on Mariko (lite), on 0.3.3, and it is stuck on the Nintendo Switch Logo.
> > FYI, Original prodinfo works.
> 
> Hi sthetix, thanks for the report! You are talking about a "from scratch" prodinfo, right?
> 
> You might well be the first to test on a Switch Lite. Could you please send me the generated prodinfo and, if possible, the original prodinfo (you can redact the certs away) at [dev@carameldunes.fr](mailto:dev@carameldunes.fr)?

I've sent you an email. Thanks!
